[env]
HK_MISE = 1

[tools]
act = "0.2.89"
bazel = "9.2.0"
buildifier = "8.5.1"
hk = "1.57.0"
rg = "15.2.0"
rust = { version = "1.98.0", profile = "default" }

[tasks.smoke_test]
run = 'bazel test --test_env=PATH //rust-reapi:smoke_test'

[hooks]
postinstall = "hk install --mise"
