load("@crates//:defs.bzl", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_library", "rust_test")
load("@rules_rust_prost//:defs.bzl", "rust_prost_library")
load("@rules_shell//shell:sh_test.bzl", "sh_test")

rust_prost_library(
    name = "remote_execution_rust",
    proto = "@bazel_remote_apis//build/bazel/remote/execution/v2:remote_execution_proto",
)

rust_prost_library(
    name = "semver_proto",
    proto = "@bazel_remote_apis//build/bazel/semver:semver_proto",
)

rust_prost_library(
    name = "status_proto",
    proto = "@googleapis//google/rpc:status_proto",
)

rust_prost_library(
    name = "bytestream_proto",
    proto = "@googleapis//google/bytestream:bytestream_proto",
)

rust_library(
    name = "rust_reapi_lib",
    srcs = ["src/lib.rs"] + glob([
        "src/services/**/*.rs",
        "src/storage/**/*.rs",
        "src/digest/**/*.rs",
    ]),
    crate_name = "rust_reapi",
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro = True),
    deps = [
        ":bytestream_proto",
        ":remote_execution_rust",
        ":semver_proto",
        ":status_proto",
    ] + all_crate_deps(
        normal = True,
    ),
)

rust_binary(
    name = "rust_reapi_cache",
    srcs = ["src/bin/cache.rs"],
    crate_root = "src/bin/cache.rs",
    edition = crate_edition(),
    deps = [
        ":bytestream_proto",
        ":remote_execution_rust",
        ":rust_reapi_lib",
    ] + all_crate_deps(normal = True),
)

rust_test(
    name = "asset_client_test",
    size = "small",
    srcs = [
        "tests/asset_client.rs",
        "tests/common/mod.rs",
    ],
    crate_root = "tests/asset_client.rs",
    edition = crate_edition(),
    deps = [
        ":bytestream_proto",
        ":remote_execution_rust",
        ":rust_reapi_lib",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test(
    name = "action_cache_test",
    size = "small",
    srcs = [
        "tests/action_cache_client.rs",
        "tests/common/mod.rs",
    ],
    crate_root = "tests/action_cache_client.rs",
    edition = crate_edition(),
    deps = [
        ":bytestream_proto",
        ":remote_execution_rust",
        ":rust_reapi_lib",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test(
    name = "capabilities_client_test",
    size = "small",
    srcs = [
        "tests/capabilities_client.rs",
        "tests/common/mod.rs",
    ],
    crate_root = "tests/capabilities_client.rs",
    edition = crate_edition(),
    deps = [
        ":bytestream_proto",
        ":remote_execution_rust",
        ":rust_reapi_lib",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test(
    name = "unit_test",
    size = "small",
    srcs = ["src/lib.rs"] + glob([
        "src/services/**/*.rs",
        "src/storage/**/*.rs",
        "src/digest/**/*.rs",
    ]),
    crate_root = "src/lib.rs",
    edition = crate_edition(),
    proc_macro_deps = all_crate_deps(proc_macro = True),
    deps = [
        ":bytestream_proto",
        ":remote_execution_rust",
        ":semver_proto",
        ":status_proto",
    ] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

sh_test(
    name = "smoke_test",
    size = "small",
    srcs = ["tests/smoke_test.sh"],
    data = [
        ":rust_reapi_cache",
        "//bazel-smoke:files",
    ],
    tags = ["manual"],
)
