[package]
name = "rust_reapi"
version = "0.1.0"
edition = "2024"

[features]
bazel_build = []

[dependencies]
tonic = "0.14.6"
prost = "0.14.4"
prost-types = "0.14.4"
tonic-prost = "0.14.6"
tokio = { version = "1.53.1", features = [
  "macros",
  "rt-multi-thread",
  "net",
  "io-util",
] }
remote_execution_proto = { path = "../rust-reapi-proto/" }
semver_proto = { path = "../semver-proto/" }
status_proto = { path = "../status-proto/" }
bytestream_proto = { path = "../bytestream-proto/" }
thiserror = "2.0.20"
zstd = "0.13.3"
sha2 = "0.10.9"
async-trait = "0.1.92"

[dev-dependencies]
tokio-stream = { version = "0.1.19", features = ["net"] }

[build-dependencies]
protoc-gen-prost = "0.5"
protoc-gen-tonic = "0.5"
